# Register/create new user
POST http://localhost:3000/api/user/create HTTP/1.1
content-type: application/json

{
  "username": "test1",
  "password": "password1",
  "email": "some@email.com"
}

###

# Login with account
POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
  "username": "test1",
  "password": "password1"
}

###

# Use JWT to access protected route
GET http://localhost:3000/api/protected HTTP/1.1
content-type: application/json
authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGI3OGViMmZkMTY4MjZhOTEyYzllNCIsImlhdCI6MTY0MTg0OTI5OSwiZXhwIjoxNjQxOTA5Mjk5fQ.slot69n2Y3II-uFbsIRZOtNtwO5grDe2-U5JHHJf63U